// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file string_.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _STRING__H_
#define _STRING__H_

// TODO Poner en el contexto.

#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif
#else
#define eProsima_user_DllExport
#endif

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(string__SOURCE)
#define string__DllAPI __declspec( dllexport )
#else
#define string__DllAPI __declspec( dllimport )
#endif // string__SOURCE
#else
#define string__DllAPI
#endif
#else
#define string__DllAPI
#endif // _WIN32

namespace eprosima
{
    namespace fastcdr
    {
        class Cdr;
    }
}

const uint8_t ARRAY_SIZE = 58;
/*!
 * @brief This class represents the structure string_ defined by the user in the IDL file.
 * @ingroup STRING_
 */
class string_
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport string_();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~string_();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object string_ that will be copied.
     */
    eProsima_user_DllExport string_(const string_ &x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object string_ that will be copied.
     */
    eProsima_user_DllExport string_(string_ &&x);

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object string_ that will be copied.
     */
    eProsima_user_DllExport string_& operator=(const string_ &x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object string_ that will be copied.
     */
    eProsima_user_DllExport string_& operator=(string_ &&x);

    /*!
     * @brief This function copies the value in member name
     * @param _name New value to be copied in member name
     */
    inline eProsima_user_DllExport void name(const std::array<char, 10> &_name)
    {
        m_name = _name;
    }

    /*!
     * @brief This function moves the value in member name
     * @param _name New value to be moved in member name
     */
    inline eProsima_user_DllExport void name(std::array<char, 10> &&_name)
    {
        m_name = std::move(_name);
    }

    /*!
     * @brief This function returns a constant reference to member name
     * @return Constant reference to member name
     */
    inline eProsima_user_DllExport const std::array<char, 10>& name() const
    {
        return m_name;
    }

    /*!
     * @brief This function returns a reference to member name
     * @return Reference to member name
     */
    inline eProsima_user_DllExport std::array<char, 10>& name()
    {
        return m_name;
    }

    /*!
     * @brief This function returns the maximum serialized size of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getMaxCdrSerializedSize(size_t current_alignment = 0);

    /*!
     * @brief This function returns the serialized size of a data depending on the buffer alignment.
     * @param data Data which is calculated its serialized size.
     * @param current_alignment Buffer alignment.
     * @return Serialized size.
     */
    eProsima_user_DllExport static size_t getCdrSerializedSize(const string_& data, size_t current_alignment = 0);


    /*!
     * @brief This function serializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serialize(eprosima::fastcdr::Cdr &cdr) const;

    /*!
     * @brief This function deserializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void deserialize(eprosima::fastcdr::Cdr &cdr);



    /*!
     * @brief This function returns the maximum serialized size of the Key of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(size_t current_alignment = 0);

    /*!
     * @brief This function tells you if the Key has been defined for this type
     */
    eProsima_user_DllExport static bool isKeyDefined();

    /*!
     * @brief This function serializes the key members of an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serializeKey(eprosima::fastcdr::Cdr &cdr) const;

private:
    std::array<char, 10> m_name;
};

#endif // _STRING__H_
