ros2_to_serial_bridge:
    ros__parameters:
        device: /dev/pts/6             # Which device to use for communications.
        baudrate: 0                    # The baudrate to set on the device; if
                                       # set to 0, setting baudrate is skipped.
        read_poll_ms: 100              # How many milliseconds to wait for new
                                       # data to come in from the serial port.
                                       # Larger numbers can use less CPU time,
                                       # but affect the responsiveness of the
                                       # program.  The default value of 100 is
                                       # a good compromise between
                                       # responsiveness and CPU time.
        ring_buffer_size: 8192         # The number of bytes to use for the
                                       # internal read buffer.  Larger values
                                       # allow larger messages to be transmitted
                                       # at the cost of more memory.
        write_sleep_ms: 4              # How many milliseconds to sleep in
                                       # between servicing ROS 2 callbacks.
                                       # Larger numbers will result in less CPU
                                       # usage but also some latency in
                                       # delivering data from ROS 2 to the
                                       # serial port.  The default of 4 ms
                                       # (250Hz) is a good compromise between
                                       # CPU time and latency.  It is not
                                       # recommended to set this above 100,
                                       # since this will cause the application
                                       # to feel sluggish.
        dynamic_serial_mapping_ms: 500 # How many milliseconds to wait to get
                                       # dynamic ROS2-to-serial mapping from the
                                       # serial side.  If less than 0, dynamic
                                       # mapping is disabled and the topics
                                       # below will be used.  If exactly 0, wait
                                       # forever for the other side to respond.
                                       # If greater than 0, wait that many
                                       # milliseconds for a response before
                                       # failing.  If this config is >= 0, the
                                       # any topics configured below will be
                                       # ignored.
        serial_protocol: cobs          # The serial protocol to use.  Currently
                                       # available protocols are 'px4'
                                       # and 'cobs'.
        topics:                        # The list of topics to map; only used
                                       # if dynamic_serial_mapping_ms is < 0.
            chatter:
                serial_mapping: 9
                type: std_msgs/String
                direction: SerialToROS2
            uint16topic:
                serial_mapping: 12
                type: std_msgs/UInt16
                direction: SerialToROS2
            another:
                serial_mapping: 13
                type: std_msgs/String
                direction: ROS2ToSerial
